Repository keycloak/keycloak-ui, pull requests merged in 2021-12, with the labels that each got.

#1634 Wait for group to be deleted before navigating
  src/groups/GroupsSection.tsx
Labels: kind/bug

#1635 Trim name of client scope before saving
  src/client-scopes/form/ClientScopeForm.tsx
Labels: kind/bug

#1639 Trim names of client, realm role, user and group before saving
  src/clients/ClientDetails.tsx
  src/clients/add/NewClientForm.tsx
  src/groups/GroupsModal.tsx
  src/realm-roles/RealmRoleTabs.tsx
  src/user/UsersTabs.tsx
Labels: kind/bug

#1661 Review comments for Cypress fixes PR
  cypress/plugins/index.ts
  package-lock.json
  package.json
Labels: kind/enhancement

#1638 Added role mapping tab to group detail page
  cypress/support/pages/admin_console/manage/groups/GroupDetailPage.ts
  package-lock.json
  package.json
  src/components/role-mapping/AddRoleMappingModal.tsx
  src/components/role-mapping/RoleMapping.tsx
  src/groups/GroupRoleMapping.tsx
  src/groups/GroupsSection.tsx
  src/groups/Members.tsx
  src/groups/messages.ts
Labels: area/needs-ux-approval, kind/feature

#1644 Complete partial import functionality.
  cypress/fixtures/partial-import-test-data/multi-realm.json
  cypress/integration/partial_import_test.spec.ts
  cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
  package-lock.json
  package.json
  src/common-messages.ts
  src/realm-settings/PartialImport.tsx
  src/realm-settings/messages.ts
Labels: kind/feature

#1789 Enable 'admin-preview' profile when building Keycloak
  .github/workflows/cypress.yml
Labels: kind/bug, priority/critical, impact/high
