Repository keycloak/keycloak-ui, pull requests merged in 2021-11, with the labels that each got.

#1473 Use route functions for navigation in authentication
  src/authentication/form/CreateFlow.tsx
Labels: enhancement

#1472 Use route functions for navigation in client scopes
  src/client-scopes/details/ScopeForm.tsx
  src/client-scopes/form/ClientScopeForm.tsx
Labels: enhancement

#1475 Use route functions for navigation in identity-providers
  src/identity-providers/add/AddIdentityProvider.tsx
  src/identity-providers/add/AddOpenIdConnect.tsx
  src/identity-providers/add/AddSamlConnect.tsx
  src/identity-providers/add/DetailSettings.tsx
Labels: enhancement

#1506 Prevent Dependabot from offering major updates for React Router
  .github/dependabot.yml
Labels: enhancement, dependencies

#1477 Ask for confirmation before unlinking users
  src/user-federation/UserFederationLdapSettings.tsx
  src/user-federation/messages.ts
Labels: enhancement, Needs UXD Approval

#1474 Use route functions for navigation in groups
  src/groups/GroupTable.tsx
  src/groups/GroupsSection.tsx
  src/groups/MembersModal.tsx
Labels: enhancement

#1530 Prevent Dependabot from offering major updates for React Router breadcrumbs
  .github/dependabot.yml
Labels: enhancement, dependencies

#1523 Split realm context into two
  src/App.tsx
  src/components/data-loader/DataLoader.test.tsx
  src/components/form-access/FormAccess.test.tsx
  src/components/realm-selector/RealmSelector.tsx
  src/context/RealmsContext.tsx
  src/context/realm-context/RealmContext.tsx
  src/realm-settings/RealmSettingsTabs.tsx
  src/realm/add/NewRealmForm.tsx
Labels: kind/enhancement

#1537 Add correct label for Dependabot PRs to config
  .github/dependabot.yml
Labels: kind/enhancement

#1509 Add user profile tab to realm settings
  src/realm-settings/RealmSettingsTabs.tsx
  src/realm-settings/UserProfileTab.tsx
  src/realm-settings/messages.ts
  src/realm-settings/routes/RealmSettings.ts
Labels: area/needs-ux-approval, kind/feature

#1565 Remove hack for mounting JSON editor
  src/realm-settings/UserProfileTab.tsx
Labels: kind/enhancement

#1569 Fix Cypress tests
  cypress/integration/events_test.spec.ts
  cypress/support/pages/admin_console/manage/events/UserEventsTab.ts
  src/context/auth/AdminClient.tsx
  src/identity-providers/IdentityProvidersSection.tsx
Labels: kind/bug, impact/high

#1571 Add Dependabot configuration for Maven
  .github/dependabot.yml
Labels: kind/enhancement, area/dependencies

#1574 Downgrade to Node 16
  .github/workflows/cypress.yml
  .github/workflows/main.yml
  keycloak-theme/pom.xml
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies

#1572 Show exact commit hash of Admin UI in interface
  keycloak-theme/pom.xml
  src/dashboard/Dashboard.tsx
  src/dashboard/messages.ts
  src/environment.ts
Labels: kind/feature, priority/important

#1598 Include .git directory to fix Docker build
  .dockerignore
Labels: kind/bug

#1575 Realm settings(Client policies): Update client-scopes condition to match new design
  cypress/integration/realm_settings_test.spec.ts
  cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
  src/client-scopes/ClientScopesSection.tsx
  src/clients/ClientDetails.tsx
  src/clients/messages.ts
  src/clients/scopes/AddScopeDialog.tsx
  src/clients/scopes/ClientScopes.tsx
  src/clients/scopes/client-scopes.css
  src/clients/utils.ts
  src/components/dynamic/MultivaluedScopesComponent.tsx
  src/realm-settings/NewClientPolicyCondition.tsx
  src/realm-settings/NewClientPolicyForm.tsx
  src/realm-settings/RealmSettingsSection.css
Labels: kind/feature

#1603 Prune older versions of published snapshots
  .github/workflows/publish.yml
Labels: kind/bug, priority/critical

#1602 Implement UXD feedback for Admin UI version
  src/dashboard/Dashboard.tsx
  src/dashboard/messages.ts
Labels: kind/enhancement, area/needs-ux-approval

#1600 Add useToggle hook to manage toggleable state
  package-lock.json
  package.json
  src/PageHeader.tsx
  src/authentication/AuthenticationSection.tsx
  src/authentication/FlowDetails.tsx
  src/authentication/components/EditFlowDropdown.tsx
  src/authentication/components/FlowRequirementDropdown.tsx
  src/authentication/components/modals/AddSubFlowModal.tsx
  src/authentication/form/FlowType.tsx
  src/client-scopes/ChangeTypeDropdown.tsx
  src/client-scopes/ClientScopesSection.tsx
  src/client-scopes/add/MapperDialog.test.tsx
  src/client-scopes/details/ScopeForm.tsx
  src/client-scopes/details/SearchFilter.tsx
  src/client-scopes/form/ClientScopeForm.tsx
  src/clients/AdvancedTab.tsx
  src/clients/ClientDetails.tsx
  src/clients/ClientSettings.tsx
  src/clients/add/GeneralSettings.tsx
  src/clients/add/SamlConfig.tsx
  src/clients/add/SamlSignature.tsx
  src/clients/advanced/AdvancedSettings.tsx
  src/clients/advanced/AuthenticationOverrides.tsx
  src/clients/advanced/FineGrainOpenIdConnect.tsx
  src/clients/advanced/TokenLifespan.tsx
  src/clients/credentials/Credentials.tsx
  src/clients/credentials/SignedJWT.tsx
  src/clients/keys/GenerateKeyDialog.tsx
  src/clients/keys/ImportKeyDialog.tsx
  src/clients/keys/Keys.tsx
  src/clients/scopes/AddScopeDialog.tsx
  src/utils/useToggle.test.ts
  src/utils/useToggle.ts
Labels: kind/enhancement
