Repository keycloak/keycloak-ui, pull requests merged in 2021-08, with the labels that each got.

#932 Update to Keycloak 15
  Dockerfile
  start.mjs
Labels: dependencies, enhancement

#938 Hide details when adaptor config is download-only
  src/components/download-dialog/DownloadDialog.tsx
Labels: bug

#933 Convert more links to use new routes
  src/PageHeader.tsx
  src/client-scopes/ClientScopesSection.tsx
  src/client-scopes/details/MapperList.tsx
  src/client-scopes/routes/ClientScope.ts
  src/events/EventsSection.tsx
  src/groups/Members.tsx
  src/realm-roles/RolesList.tsx
  src/realm-roles/routes/RealmRole.ts
  src/realm-settings/RealmSettingsSection.tsx
  src/user/UsersSection.tsx
  src/user/routes/User.ts
Labels: enhancement

#978 Update Keycloak to version 15.0.1
  Dockerfile
  start.mjs
Labels: enhancement, dependencies

#980 Use correct default for 'Truststore SPI'
  src/user-federation/ldap/LdapSettingsConnection.tsx
Labels: enhancement

#990 Fix realm intialization
  src/App.tsx
  src/KeycloakAdminConsole.tsx
  src/context/realm-context/RealmContext.tsx
  src/index.tsx
Labels: bug

#992 Prefer optional chaining over validating references
  .eslintrc.js
  src/clients/ClientSettings.tsx
  src/clients/credentials/X509.tsx
  src/components/attribute-form/AttributeForm.tsx
  src/components/multi-line-input/MultiLineInput.tsx
  src/components/table-toolbar/KeycloakDataTable.tsx
  src/components/table-toolbar/TableToolbar.tsx
  src/context/whoami/WhoAmI.tsx
  src/identity-providers/add/AdvancedSettings.tsx
  src/identity-providers/add/DiscoverySettings.tsx
  src/identity-providers/add/OpenIdConnectSettings.tsx
  src/identity-providers/component/ClientIdSecret.tsx
  src/realm-roles/RoleAttributes.tsx
  src/user-federation/kerberos/KerberosSettingsRequired.tsx
  src/user-federation/ldap/LdapSettingsConnection.tsx
  src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
  src/user-federation/ldap/LdapSettingsSearching.tsx
  src/user-federation/ldap/mappers/LdapMapperHardcodedLdapGroup.tsx
  src/user-federation/ldap/mappers/LdapMapperHardcodedLdapRole.tsx
  src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx
  src/user/UserGroups.tsx
Labels: enhancement, 24h Review Period

#1000 changed save buttons from `tertiary` to `secondary`
  src/clients/advanced/AdvancedSettings.tsx
  src/clients/advanced/AuthenticationOverrides.tsx
  src/clients/advanced/FineGrainOpenIdConnect.tsx
  src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
Labels: Needs UXD Approval

#999 fixed focus and min value
  src/clients/advanced/TokenLifespan.tsx
  src/components/time-selector/TimeSelector.tsx
Labels: Needs UXD Approval

#998 fixed breadcrumb for search and seach box distance
  src/components/bread-crumb/GroupBreadCrumbs.tsx
  src/groups/SearchGroups.tsx
Labels: Needs UXD Approval

#1009 Disable major updates of broken dependencies
  .github/dependabot.yml
Labels: enhancement, dependencies

#1008 Fix CVEs from NPM audit
  package-lock.json
Labels: dependencies, security

#1013 Prefer Array#includes() over Array#indexOf()
  .eslintrc.js
  src/clients/ClientsSection.tsx
  src/components/bread-crumb/GroupBreadCrumbs.tsx
  src/components/keycloak-tabs/KeycloakTabs.tsx
  src/identity-providers/add/DetailSettings.tsx
  src/user-federation/ldap/mappers/LdapMapperList.tsx
Labels: enhancement, 24h Review Period

#1023 Add a constant for the default locale
  src/context/whoami/WhoAmI.tsx
  src/i18n.ts
  src/realm-settings/LocalizationTab.tsx
Labels: enhancement

#930 events: search user events form, chips for searched fields and tests
  cypress/integration/events_test.spec.ts
  cypress/support/pages/admin_console/manage/events/EventsPage.ts
  src/events/EventsSection.tsx
  src/events/events-section.css
  src/events/messages.ts
Labels: enhancement, Needs UXD Approval

#1026 Process UXD review for Client Scopes
  src/client-scopes/ClientScopesSection.tsx
  src/client-scopes/details/ScopeForm.tsx
  src/client-scopes/messages.ts
Labels: enhancement, Needs UXD Approval

#1028 Update Keycloak to version 15.0.2
  Dockerfile
  start.mjs
Labels: dependencies

#1065 Cache NPM dependencies in workflows
  .github/workflows/cypress.yml
  .github/workflows/node.js.yml
Labels: enhancement
