Repository keycloak/keycloak-ui, pull requests merged in 2021-10, with the labels that each got.

#1278 Remove ability to delete a realm client from the overview
  src/clients/ClientDetails.tsx
  src/clients/ClientsSection.tsx
  src/clients/utils.ts
Labels: enhancement, Needs UXD Approval

#1280 Use type-safe alternative for links
  src/PageHeader.tsx
  src/authentication/AuthenticationSection.tsx
  src/client-scopes/ClientScopesSection.tsx
  src/client-scopes/details/MappingDetails.tsx
  src/clients/ClientsSection.tsx
  src/clients/import/ImportForm.tsx
  src/clients/initial-access/CreateInitialAccessToken.tsx
  src/clients/initial-access/InitialAccessTokenList.tsx
  src/identity-providers/add/DetailSettings.tsx
  src/realm-settings/NewClientProfileForm.tsx
  src/realm-settings/ProfilesTab.tsx
Labels: enhancement

#1283 Add a human readable name for client protocol
  cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
  src/client-scopes/details/ScopeForm.tsx
  src/clients/ClientDetails.tsx
  src/clients/ClientsSection.tsx
  src/clients/add/GeneralSettings.tsx
  src/clients/help.ts
  src/clients/messages.ts
  src/clients/utils.ts
Labels: enhancement, Needs UXD Approval

#1287 Prefer using arrow functions for callbacks
  .eslintrc.js
  cypress/integration/client_scopes_test.spec.ts
  cypress/integration/clients_test.spec.ts
  cypress/integration/identity_providers.spec.ts
  cypress/integration/login_test.spec.ts
  cypress/integration/realm_roles_test.spec.ts
  cypress/integration/realm_settings_test.spec.ts
  cypress/integration/sessions_test.spec.ts
  src/authentication/components/diagram/ConditionalNode.tsx
  src/authentication/components/diagram/SubFlowNode.tsx
Labels: enhancement

#1284 Client add executors
  cypress/integration/realm_settings_test.spec.ts
  cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
  src/realm-settings/NewClientProfileForm.tsx
  src/realm-settings/ProfilesTab.tsx
  src/realm-settings/RealmSettingsSection.css
  src/realm-settings/messages.ts
Labels: 24h Review Period

#1279 Hide capability config for bearer-only clients
  cypress/integration/clients_test.spec.ts
  src/clients/ClientDetails.tsx
  src/clients/ClientSettings.tsx
  src/clients/add/CapabilityConfig.tsx
  src/components/scroll-form/ScrollForm.tsx
Labels: enhancement, Needs UXD Approval

#1442 Normalize client attributes before saving
  src/clients/add/NewClientForm.tsx
Labels: bug
