Repository keycloak/keycloak-ui, pull requests merged in 2021-09, with the labels that each got.

#1129 Link to RealmRoleRoute using a static path
  src/realm-roles/RolesList.tsx
  src/realm-roles/routes/ClientRole.ts
  src/realm-roles/routes/RealmRole.ts
Labels: enhancement

#1130 Keep realm value from RealmContext in sync with the URL
  src/components/data-loader/DataLoader.test.tsx
  src/components/form-access/FormAccess.test.tsx
  src/components/realm-selector/RealmSelector.tsx
  src/context/realm-context/RealmContext.tsx
  src/realm-settings/RealmSettingsTabs.tsx
  src/realm/add/NewRealmForm.tsx
Labels: bug

#1127 Warn about unnecessary conditions
  .eslintrc.js
Labels: enhancement

#1054 Add action to automatically publish snapshots
  .github/workflows/publish.yml
  keycloak-theme/pom.xml
Labels: enhancement, do not merge

#1137 Admin events rep dialog
  package-lock.json
  package.json
  src/events/AdminEvents.tsx
  src/realm-settings/PoliciesTab.tsx
  src/realm-settings/ProfilesTab.tsx
  src/realm-settings/RealmSettingsSection.css
  src/realm-settings/RealmSettingsTabs.tsx
  src/realm-settings/messages.ts
  src/realm-settings/routes/RealmSettings.ts
Labels: 24h Review Period

#1138 Remove internationalization from 'Themes' tab
  src/realm-settings/RealmSettingsTabs.tsx
  src/realm-settings/ThemesTab.tsx
Labels: enhancement, Needs UXD Approval

#1139 Process UXD feedback for client revocation
  cypress/integration/clients_test.spec.ts
  src/clients/AdvancedTab.tsx
  src/clients/help.ts
Labels: enhancement, Needs UXD Approval

#1148 Stop running unit tests on commit
  .husky/pre-commit
Labels: enhancement

#1152 don't show toolbar when not searching
  cypress/integration/client_scopes_test.spec.ts
  cypress/integration/events_test.spec.ts
  cypress/integration/group_test.spec.ts
  cypress/integration/realm_settings_test.spec.ts
  cypress/integration/users_test.spec.ts
  cypress/support/pages/admin_console/SidebarPage.ts
  src/components/table-toolbar/KeycloakDataTable.tsx
  src/realm-settings/LocalizationTab.tsx
Labels: bug

#1167 Lint all files in the project
  .eslintrc.js
  cypress/integration/user_fed_ldap_test.spec.ts
  cypress/plugins/index.js
  cypress/support/pages/admin_console/manage/RoleMappingTab.ts
  cypress/support/pages/admin_console/manage/realm_roles/CreateRealmRolePage.ts
  cypress/support/pages/admin_console/manage/users/UserDetailsPage.ts
  cypress/support/util/keycloak_before.ts
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  postcss.config.js
  tsconfig.eslint.json
  types/import.d.ts
  types/static.d.ts
Labels: enhancement, dependencies

#1169 Prevent publish from running on forked repositories
  .github/workflows/publish.yml
Labels: enhancement

#1178 Check types using ts-jest and upgrade Jest
  .github/dependabot.yml
  jest.config.ts
  jest.setup.ts
  mocks/fileMock.js
  mocks/fileMock.ts
  mocks/styleMock.js
  package-lock.json
  package.json
  src/authentication/__tests__/ExecutionList.test.ts
  src/client-scopes/add/MapperDialog.test.tsx
  src/components/confirm-dialog/ConfirmDialog.test.tsx
  src/components/data-loader/DataLoader.test.tsx
  src/components/form-access/FormAccess.test.tsx
  src/context/whoami/__tests__/WhoAmI.test.ts
  tsconfig.jest.json
Labels: enhancement, dependencies

#1168 Configure Cypress to use the correct types
  cypress/integration/events_test.spec.ts
  cypress/integration/realm_settings_test.spec.ts
  cypress/integration/users_test.spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/support/pages/ViewHeaderPage.ts
  cypress/support/pages/admin_console/RealmSelector.ts
  cypress/support/pages/admin_console/SidebarPage.ts
  cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
  cypress/support/pages/admin_console/configure/realm_settings/RealmSettings.ts
  cypress/support/pages/admin_console/manage/RoleMappingTab.ts
  cypress/support/pages/admin_console/manage/authentication/DuplicateFlowModal.ts
  cypress/support/pages/admin_console/manage/authentication/FlowDetail.ts
  cypress/support/pages/admin_console/manage/clients/AdvancedTab.ts
  cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
  cypress/support/pages/admin_console/manage/clients/InitialAccessTokenTab.ts
  cypress/support/pages/admin_console/manage/clients/KeysTab.ts
  cypress/support/pages/admin_console/manage/events/AdminEventsTab.ts
  cypress/support/pages/admin_console/manage/events/UserEventsTab.ts
  cypress/support/pages/admin_console/manage/groups/GroupDetailPage.ts
  cypress/support/pages/admin_console/manage/groups/GroupModal.ts
  cypress/support/pages/admin_console/manage/groups/MoveGroupModal.ts
  cypress/support/pages/admin_console/manage/groups/SearchGroup.ts
  cypress/support/pages/admin_console/manage/identity_providers/AddMapperPage.ts
  cypress/support/pages/admin_console/manage/identity_providers/CreateProviderPage.ts
  cypress/support/pages/admin_console/manage/identity_providers/OrderDialog.ts
  cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
  cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
  cypress/support/pages/admin_console/manage/realm_roles/CreateRealmRolePage.ts
  cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
  cypress/support/pages/admin_console/manage/sessions/SessionsPage.ts
  cypress/support/pages/admin_console/manage/users/CreateUserPage.ts
  cypress/support/pages/admin_console/manage/users/UserDetailsPage.ts
  cypress/support/pages/admin_console/manage/users/UserGroupsPage.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  tsconfig.jest.json
  tsconfig.json
  types/import.d.ts
Labels: enhancement, dependencies

#1186 Check types when running Cypress
  cypress/plugins/index.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: enhancement, dependencies

#1207 Run the Cypress tests on master of Keycloak Server
  .github/workflows/cypress.yml
Labels: enhancement

#1211 Clean up workflows a little
  .github/workflows/cypress.yml
  .github/workflows/main.yml
  .github/workflows/node.js.yml
  .github/workflows/publish.yml
Labels: enhancement

#1238 Prevent Dependabot from automatically rebasing
  .github/dependabot.yml
Labels: enhancement

#1222 Run jobs for CI in parallel
  .github/workflows/main.yml
Labels: enhancement

#1244 Show a tooltip to explain bearer-only clients
  src/clients/ClientDetails.tsx
  src/clients/messages.ts
Labels: enhancement, Needs UXD Approval

#1245 Hide certain elements on the page if client is a realm
  cypress/integration/clients_test.spec.ts
  src/clients/ClientDetails.tsx
Labels: enhancement, Needs UXD Approval

#1266 Add help text to the realm localization fields
  src/realm-settings/LocalizationTab.tsx
  src/realm-settings/help.ts
Labels: enhancement, Needs UXD Approval

#1270 Add tests for bearer-only client details
  cypress/integration/clients_test.spec.ts
  src/clients/ClientDetails.tsx
Labels: enhancement

#1269 Correct help text for XSS protection header
  src/realm-settings/help.ts
Labels: enhancement

#1274 Improve caching logic of main workflow
  .github/workflows/main.yml
Labels: enhancement
