Repository keycloak/keycloak-ui, pull requests merged in 2022-02, with the labels that each got.

#1990 Replace Lodash with it's ESM variant
  .eslintrc.js
  cypress/support/pages/admin_console/SidebarPage.ts
  cypress/support/util/AdminClient.ts
  jest.config.ts
  package-lock.json
  package.json
  src/authentication/components/DraggableTable.tsx
  src/clients/ClientDetails.tsx
  src/clients/advanced/AuthenticationOverrides.tsx
  src/components/attribute-input/AttributeInput.tsx
  src/components/bread-crumb/PageBreadCrumbs.tsx
  src/components/dynamic/MultivaluedRoleComponent.tsx
  src/components/role-mapping/AddRoleMappingModal.tsx
  src/components/table-toolbar/KeycloakDataTable.tsx
  src/context/RealmsContext.tsx
  src/dashboard/Dashboard.tsx
  src/events/AdminEvents.tsx
  src/events/EventsSection.tsx
  src/groups/Members.tsx
  src/groups/MembersModal.tsx
  src/identity-providers/IdentityProvidersSection.tsx
  src/identity-providers/ManageOrderDialog.tsx
  src/realm-roles/AssociatedRolesModal.tsx
  src/realm-roles/RealmRoleTabs.tsx
  src/realm-settings/LocalizationTab.tsx
  src/realm-settings/NewClientPolicyCondition.tsx
  src/realm-settings/ProfilesTab.tsx
  src/user-federation/kerberos/KerberosSettingsRequired.tsx
  src/user-federation/ldap/LdapSettingsConnection.tsx
  src/user-federation/shared/SettingsCache.tsx
  src/user/UserConsents.tsx
  src/user/UserGroups.tsx
  src/user/UserIdPModal.tsx
  src/user/UserIdentityProviderLinks.tsx
  src/util.ts
  src/utils/useRequiredContext.test.ts
Labels: kind/enhancement, area/dependencies

#2002 Fix message for access token response claim in new admin ui
  src/components/dynamic/labels.ts
Labels: kind/bug

#1951 Re-use User Profile logic from shared context
  src/realm-settings/user-profile/AttributesGroupTab.tsx
  src/realm-settings/user-profile/JsonEditorTab.tsx
  src/realm-settings/user-profile/UserProfileContext.tsx
  src/realm-settings/user-profile/UserProfileTab.tsx
Labels: kind/enhancement

#2089 Tweak some settings to (hopefully) fix package pruning
  .github/workflows/publish.yml
Labels: kind/bug

#2105 Update Keycloak development server to version 17.0.0
  Dockerfile
  start.mjs
Labels: kind/enhancement, area/dependencies

#2134 Add 'useSetTimeout' hook to manage timers
  src/components/alert/Alerts.tsx
  src/utils/useSetTimeout.test.ts
  src/utils/useSetTimeout.ts
Labels: kind/enhancement

#2142 Speed up CI by skipping account v2 theme in build
  .github/workflows/cypress.yml
Labels: kind/enhancement, area/integration-tests

#2140 Use a single admin client instance for all tests
  cypress/integration/authentication_test.spec.ts
  cypress/integration/client_authorization_test.spec.ts
  cypress/integration/client_scopes_test.spec.ts
  cypress/integration/clients_saml_test.spec.ts
  cypress/integration/clients_test.spec.ts
  cypress/integration/group_test.spec.ts
  cypress/integration/partial_export_test.spec.ts
  cypress/integration/partial_import_test.spec.ts
  cypress/integration/realm_roles_test.spec.ts
  cypress/integration/realm_settings_client_policies_test.spec.ts
  cypress/integration/realm_settings_client_profiles_test.spec.ts
  cypress/integration/realm_settings_events_test.spec.ts
  cypress/integration/realm_settings_tabs_test.spec.ts
  cypress/integration/realm_settings_user_profile_tab.spec.ts
  cypress/integration/realm_test.spec.ts
  cypress/integration/realm_user_registration.spec.ts
  cypress/integration/users_test.spec.ts
  cypress/support/util/AdminClient.ts
Labels: kind/enhancement, area/integration-tests

#2141 Run Cypress tests on Chrome when running headlessly
  package.json
Labels: kind/enhancement, area/integration-tests

#2147 Allow access to clipboard in Cypress tests
  cypress/support/pages/admin_console/manage/clients/AuthorizationTab.ts
  cypress/support/util/grantClipboardAccess.ts
Labels: kind/bug, priority/critical, area/integration-tests
