Repository keycloak/keycloak-ui, pull requests merged in 2022-08, with the labels that each got.

#2936 Replace Snowpack with Vite
  .eslintrc.js
  .gitignore
  README.md
  cypress/tsconfig.json
  index.html
  keycloak-theme/pom.xml
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.svg
  public/logo.svg
  snowpack.config.mjs
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  themes/keycloak/favicon.ico
  themes/keycloak/index.html
  themes/rh-sso/favicon.ico
  themes/rh-sso/index.html
  themes/rh-sso/logo.svg
  tsconfig.eslint.json
  tsconfig.json
  tsconfig.node.json
  types/static.d.ts
  vite.config.ts
Labels: kind/enhancement, area/dependencies

#3038 Remove unused WorkInProgress component
  src/components/work-in-progress/WorkInProgress.tsx
  src/components/work-in-progress/work-in-progress.css
Labels: kind/enhancement

#3039 Clean up CSS for index.html
  index.html
Labels: kind/enhancement

#3032 Add display names to contexts
  src/App.tsx
  src/components/alert/Alerts.tsx
  src/components/data-loader/DataLoader.test.tsx
  src/components/help-enabler/HelpHeader.tsx
  src/context/RealmsContext.tsx
  src/context/access/Access.tsx
  src/context/auth/AdminClient.tsx
  src/context/realm-context/RealmContext.tsx
  src/context/server-info/ServerInfoProvider.tsx
  src/context/whoami/WhoAmI.tsx
  src/groups/SubGroupsContext.tsx
  src/realm-settings/user-profile/UserProfileContext.tsx
  src/utils/createNamedContext.ts
Labels: kind/enhancement

#3060 Add utility function to join paths
  src/utils/joinPath.test.ts
  src/utils/joinPath.ts
Labels: kind/enhancement

#3112 Apply migrations for React Router 5.1
  src/App.tsx
Labels: kind/enhancement

#3058 Fix homepage URL rendering in client list
  src/clients/ClientsSection.tsx
Labels: kind/bug, area/section/clients, area/admin/ui

#3113 Use CompatRoute for routes that can be migrated
  src/App.tsx
  src/authentication/routes/Authentication.ts
  src/authentication/routes/Flow.ts
  src/client-scopes/routes/ClientScope.ts
  src/clients/routes/Clients.ts
  src/clients/routes/DedicatedScopeDetails.ts
  src/clients/routes/NewPermission.ts
  src/clients/routes/Resource.ts
  src/clients/routes/Scope.ts
  src/dashboard/routes/Dashboard.ts
  src/events/routes/Events.ts
  src/groups/routes/Groups.tsx
  src/realm-roles/routes/ClientRole.ts
  src/realm-roles/routes/RealmRole.ts
  src/realm-settings/routes/AddCondition.ts
  src/realm-settings/routes/EditCondition.ts
  src/realm-settings/routes/RealmSettings.ts
  src/route-config.ts
  src/user-federation/routes/UserFederationLdap.ts
  src/user/routes/Users.ts
Labels: kind/enhancement

#3114 Use 'useLocation' hook from v6 API of React Router
  src/components/routable-tabs/RoutableTabs.tsx
  src/groups/GroupAttributes.tsx
  src/groups/GroupTable.tsx
  src/groups/GroupsSection.tsx
  src/groups/Members.tsx
  src/groups/components/GroupTree.tsx
Labels: kind/enhancement

#3045 Update PatternFly to latest version
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies, impact/low, area/admin/ui

#3158 Revert back to 'skipTests' to fix Maven build
  .github/workflows/cypress.yml
Labels: kind/bug

#3148 Do not display error when policy name is empty
  src/realm-settings/NewClientPolicyForm.tsx
Labels: kind/bug, area/admin/ui

#3159 Use Link component from new React Router API
  src/PageHeader.tsx
  src/authentication/AuthenticationSection.tsx
  src/authentication/form/CreateFlow.tsx
  src/client-scopes/ClientScopesSection.tsx
  src/client-scopes/details/MapperList.tsx
  src/client-scopes/details/MappingDetails.tsx
  src/client-scopes/details/ScopeForm.tsx
  src/clients/ClientsSection.tsx
  src/clients/advanced/RevocationPanel.tsx
  src/clients/authorization/AuthorizationEvaluateResourcePolicies.tsx
  src/clients/authorization/DetailDescription.tsx
  src/clients/authorization/PermissionDetails.tsx
  src/clients/authorization/Permissions.tsx
  src/clients/authorization/Policies.tsx
  src/clients/authorization/ResourceDetails.tsx
  src/clients/authorization/Resources.tsx
  src/clients/authorization/ScopeDetails.tsx
  src/clients/authorization/Scopes.tsx
  src/clients/authorization/policy/PolicyDetails.tsx
  src/clients/import/ImportForm.tsx
  src/clients/initial-access/CreateInitialAccessToken.tsx
  src/clients/initial-access/InitialAccessTokenList.tsx
  src/clients/scopes/ClientScopes.tsx
  src/clients/service-account/ServiceAccount.tsx
  src/components/bread-crumb/GroupBreadCrumbs.tsx
  src/components/bread-crumb/PageBreadCrumbs.tsx
  src/components/permission-tab/PermissionTab.tsx
  src/events/EventsSection.tsx
  src/events/ResourceLinks.tsx
  src/groups/GroupTable.tsx
  src/groups/GroupsSection.tsx
  src/groups/Members.tsx
  src/groups/SearchGroups.tsx
  src/identity-providers/IdentityProvidersSection.tsx
  src/identity-providers/add/AddIdentityProvider.tsx
  src/identity-providers/add/AddMapper.tsx
  src/identity-providers/add/AddOpenIdConnect.tsx
  src/identity-providers/add/AddSamlConnect.tsx
  src/identity-providers/add/DetailSettings.tsx
  src/realm-roles/RolesList.tsx
  src/realm-settings/ClientProfileForm.tsx
  src/realm-settings/DefaultGroupsTab.tsx
  src/realm-settings/ExecutorForm.tsx
  src/realm-settings/NewAttributeSettings.tsx
  src/realm-settings/NewClientPolicyForm.tsx
  src/realm-settings/PoliciesTab.tsx
  src/realm-settings/ProfilesTab.tsx
  src/realm-settings/keys/KeysProvidersTab.tsx
  src/realm-settings/user-profile/AttributesGroupForm.tsx
  src/realm-settings/user-profile/AttributesGroupTab.tsx
  src/realm-settings/user-profile/AttributesTab.tsx
  src/sessions/SessionsTable.tsx
  src/user-federation/custom/CustomProviderSettings.tsx
  src/user-federation/ldap/mappers/LdapMapperList.tsx
  src/user/UserIdentityProviderLinks.tsx
  src/user/UsersSection.tsx
Labels: kind/enhancement, area/admin/ui

#3145 Enable client consent text when client consent is enabled
  cypress/e2e/client_scopes_test.spec.ts
  cypress/support/pages/admin_console/manage/client_scopes/CreateClientScopePage.ts
  src/client-scopes/details/ScopeForm.tsx
  src/clients/add/LoginSettingsPanel.tsx
Labels: kind/bug, status/hold, area/admin/ui

#3167 Add extended fields for identity providers
  public/resources/en/identity-providers-help.json
  public/resources/en/identity-providers.json
  src/identity-providers/add/AddIdentityProvider.tsx
  src/identity-providers/add/DetailSettings.tsx
  src/identity-providers/component/ExtendedFieldsForm.tsx
Labels: kind/bug, area/section/identity providers, area/admin/ui

#3169 Remove Cypress test exclusion
  .eslintrc.js
  cypress/e2e/clients_test.spec.ts
  cypress/support/util/AdminClient.ts
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies, area/integration-tests, area/admin/ui

#3192 Fix path to Cypress in ESLint config
  .eslintrc.js
Labels: kind/bug, area/admin/ui

#3223 Upgrade TypeScript to latest version
  apps/admin-ui/src/authentication/components/DraggableTable.tsx
  apps/admin-ui/src/components/alert/Alerts.tsx
  apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
  apps/admin-ui/src/util.ts
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies

#3224 Set Dependabot versioning strategy for NPM
  .github/dependabot.yml
Labels: kind/bug, area/dependencies

#3229 Update dependencies to latest versions
  apps/admin-ui/package.json
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies

#3250 Regenerate package lockfile
  apps/admin-ui/package.json
  apps/admin-ui/vite.config.ts
  package-lock.json
Labels: kind/enhancement, area/dependencies

#3237 Add explainer for disabled 'Create permission' dropdown
  apps/admin-ui/public/resources/en/clients.json
  apps/admin-ui/src/clients/authorization/Permissions.tsx
Labels: kind/enhancement, area/section/clients, area/admin/ui
