Repository keycloak/keycloak-ui, pull requests merged in 2022-05, with the labels that each got.

#2559 Remove unused 'cli-progress' dependency
  package-lock.json
  package.json
Labels: kind/enhancement, dependencies

#2558 Update outdated links with redirects
  src/clients/add/SamlSignature.tsx
  src/realm-settings/security-defences/HeadersForm.tsx
Labels: kind/enhancement

#2566 Update to Jest 28
  package-lock.json
  package.json
  tsconfig.jest.json
Labels: kind/enhancement, dependencies

#2613 Update PatternFly dependencies to latest version
  package-lock.json
  package.json
  src/components/time-selector/TimeSelector.tsx
Labels: area/dependencies

#2616 Lock React and related dependencies to version 17
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies

#2621 Fix client import form state
  src/clients/import/ImportForm.tsx
Labels: kind/bug, area/section/clients

#2617 Replace text areas with KeycloakTextArea
  src/authentication/form/NameDescription.tsx
  src/client-scopes/details/ScopeForm.tsx
  src/clients/ClientDescription.tsx
  src/clients/ClientSettings.tsx
  src/clients/authorization/AuthorizationExport.tsx
  src/clients/authorization/PermissionDetails.tsx
  src/clients/authorization/policy/NameDescription.tsx
  src/clients/keys/Certificate.tsx
  src/clients/scopes/GeneratedCodeTab.tsx
  src/components/download-dialog/DownloadDialog.tsx
  src/components/keycloak-text-area/KeycloakTextArea.tsx
  src/realm-roles/RealmRoleForm.tsx
  src/realm-settings/ClientProfileForm.tsx
  src/realm-settings/NewClientPolicyForm.tsx
Labels: kind/enhancement

#2629 Upgrade to PF 4.194
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies

#2706 Use correct field for authentication of e-mail server
  src/realm-settings/EmailTab.tsx
Labels: kind/bug, area/section/realm settings

#2718 Use cy.wait() instead of cy.waitFor()
  cypress/integration/clients_saml_test.spec.ts
Labels: kind/bug, area/integration-tests
