Repository keycloak/keycloak-ui, pull requests merged in 2022-06, with the labels that each got.

#2725 Move 'Sessions' tab before 'Permissions' tab
  src/clients/ClientDetails.tsx
Labels: kind/enhancement, area/ux-review, area/section/clients

#2724 Remove arbitrary margin from bottom of forms
  src/components/scroll-form/form-panel.css
  src/index.css
Labels: kind/bug, area/ux-review

#2734 Disallow deletion of restricted user attributes
  src/authentication/components/DraggableTable.tsx
  src/realm-settings/user-profile/AttributesTab.tsx
Labels: kind/bug, area/ux-review, area/section/realm settings

#2733 Link security header help text to MDN
  src/realm-settings/security-defences/HeadersForm.tsx
Labels: kind/bug, area/section/realm settings

#2732 Add a 'Reset' button the the events search form
  public/resources/en/events.json
  src/events/AdminEvents.tsx
  src/events/EventsSection.tsx
Labels: kind/enhancement, area/ux-review, area/section/events

#2577 #11851 Use new parameter useRealmDefaultLocaleFallback when fetching the realm localization texts
  src/i18n.ts
Labels: area/needs-api, kind/feature, status/hold, status/needs-discussion

#2790 Upgrade to version 10 of Cypress
  .github/workflows/cypress.yml
  README.md
  cypress.config.ts
  cypress.json
  cypress/e2e/authentication_policies.spec.ts
  cypress/e2e/authentication_test.spec.ts
  cypress/e2e/client_authorization_test.spec.ts
  cypress/e2e/client_scopes_test.spec.ts
  cypress/e2e/clients_saml_test.spec.ts
  cypress/e2e/clients_test.spec.ts
  cypress/e2e/events_test.spec.ts
  cypress/e2e/group_test.spec.ts
  cypress/e2e/identity_providers_oidc_test.spec.ts
  cypress/e2e/identity_providers_saml_test.spec.ts
  cypress/e2e/identity_providers_test.spec.ts
  cypress/e2e/login_test.spec.ts
  cypress/e2e/masthead_test.spec.ts
  cypress/e2e/partial_export_test.spec.ts
  cypress/e2e/partial_import_test.spec.ts
  cypress/e2e/realm_roles_test.spec.ts
  cypress/e2e/realm_settings_client_policies_test.spec.ts
  cypress/e2e/realm_settings_client_profiles_test.spec.ts
  cypress/e2e/realm_settings_events_test.spec.ts
  cypress/e2e/realm_settings_general_tab_test.spec.ts
  cypress/e2e/realm_settings_tabs_test.spec.ts
  cypress/e2e/realm_settings_user_profile_tab.spec.ts
  cypress/e2e/realm_test.spec.ts
  cypress/e2e/realm_user_registration.spec.ts
  cypress/e2e/sessions_test.spec.ts
  cypress/e2e/user_fed_kerberos_test.spec.ts
  cypress/e2e/user_fed_ldap_hardcoded_mapper_test.spec.ts
  cypress/e2e/user_fed_ldap_mapper_test.spec.ts
  cypress/e2e/user_fed_ldap_test.spec.ts
  cypress/e2e/users_test.spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
  cypress/tsconfig.json
  images/cypress-test-runner.png
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies, area/integration-tests

#2805 Run code quality check on a nightly schedule
  .github/workflows/codeql-analysis.yml
Labels: kind/enhancement

#2866 Upgrade to latest version of PatternFly
  cypress/support/pages/admin_console/ListingPage.ts
  cypress/support/pages/admin_console/components/TableToolbarPage.ts
  package-lock.json
  package.json
  src/components/keycloak-text-area/KeycloakTextArea.tsx
Labels: kind/enhancement, area/dependencies

#2882 Replace .hasOwn() with .hasOwnProperty()
  src/util.ts
Labels: kind/bug

#2890 Fix compilation of tests
  cypress/support/pages/admin_console/manage/authentication/BindFlowModal.ts
Labels: kind/bug, impact/high, area/integration-tests

#2894 Replace Webpack Cypress type checks with TypeScript compiler
  .github/workflows/main.yml
  cypress.config.ts
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies, area/integration-tests

#2891 Use Cypress drag-drop package for all interactions
  cypress/support/pages/admin_console/manage/identity_providers/OrderDialog.ts
  cypress/support/pages/admin_console/manage/providers/PriorityDialog.ts
Labels: kind/enhancement, area/integration-tests
