Repository keycloak/keycloak-ui, pull requests merged in 2022-07, with the labels that each got.

#2919 Skip tests that are failing often
  cypress/e2e/identity_providers_test.spec.ts
  cypress/e2e/user_fed_ldap_test.spec.ts
Labels: kind/bug, area/integration-tests

#2920 Update PatternFly dependencies to latest version
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies

#2924 Skip broken 'assign role' test
  cypress/e2e/client_scopes_test.spec.ts
Labels: kind/bug, area/integration-tests

#2929 Replace Jest with Vitest
  jest.config.ts
  package-lock.json
  package.json
  src/authentication/__tests__/ExecutionList.test.ts
  src/authentication/policies/util.test.ts
  src/components/confirm-dialog/ConfirmDialog.test.tsx
  src/components/data-loader/DataLoader.test.tsx
  src/components/form-access/FormAccess.test.tsx
  src/components/key-value-form/key-value-convert.test.ts
  src/components/time-selector/time-selector.test.ts
  src/context/whoami/__tests__/WhoAmI.test.ts
  src/util.test.ts
  src/utils/isDefined.test.ts
  src/utils/useRequiredContext.test.ts
  src/utils/useSetTimeout.test.ts
  src/utils/useToggle.test.ts
  tsconfig.jest.json
  vite.config.ts
  vitest.setup.ts
Labels: kind/enhancement, area/dependencies

#2937 Lock Snowpack to older version to prevent compilation issues
  package-lock.json
  package.json
Labels: kind/bug, area/dependencies

#2956 Preprocess Cypress tests with Vite
  cypress.config.ts
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies, area/integration-tests

#2959 Fix Masthead tests
  cypress/support/pages/admin_console/Masthead.ts
Labels: kind/bug, area/integration-tests

#2957 Use ES module version of the Admin Client
  package-lock.json
  package.json
  scripts/import-client.mjs
Labels: kind/enhancement, area/dependencies

#2971 Replace CI trigger for Cypress
  .github/workflows/cypress.yml
Labels: kind/bug, area/integration-tests

#2985 Support for post_logout_redirect_uris in OIDC client registration
  public/resources/en/clients-help.json
  public/resources/en/clients.json
  src/clients/ClientDetails.tsx
  src/clients/add/AccessSettings.tsx
Labels: kind/enhancement

#2997 Build Cypress tests with WebPack
  cypress.config.mjs
  cypress.config.ts
  package-lock.json
  package.json
Labels: kind/enhancement, area/dependencies, priority/critical
